"use client"
import { FileBarChart, Download, RefreshCw } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"

const reportCards = [
  { title: "Monthly District Report", desc: "District-wise KPIs: screened, spectacles, referrals, SLA", period: "May 2024", size: "2.4 MB", type: "PDF" },
  { title: "Statewide KPI Report", desc: "Complete AP-level eye care program statistics", period: "Q4 FY2023-24", size: "5.1 MB", type: "XLSX" },
  { title: "ABDM Statistics", desc: "Ayushman Bharat Digital Mission compliance report", period: "May 2024", size: "1.8 MB", type: "PDF" },
  { title: "Vendor SLA Report", desc: "Vendor-wise order fulfillment and SLA compliance", period: "May 2024", size: "0.9 MB", type: "PDF" },
  { title: "Disease Burden Report", desc: "AI-generated disease prevalence and hotspot analysis", period: "Jun 2024", size: "3.2 MB", type: "PDF" },
]

const recentReports = [
  { id: "rep001", name: "May 2024 District Report - All", generated: "2024-06-01", by: "Admin Suresh", size: "2.4 MB", status: "Ready" },
  { id: "rep002", name: "Q4 FY23-24 Statewide KPI", generated: "2024-05-31", by: "Admin Suresh", size: "5.1 MB", status: "Ready" },
  { id: "rep003", name: "Apr 2024 Vendor SLA Report", generated: "2024-05-03", by: "Admin Suresh", size: "0.8 MB", status: "Ready" },
  { id: "rep004", name: "Disease Burden Analysis - Jun 2024", generated: "2024-06-05", by: "System AI", size: "3.2 MB", status: "Ready" },
  { id: "rep005", name: "ABDM Statistics Q4 FY23-24", generated: "2024-05-28", by: "Admin Suresh", size: "1.8 MB", status: "Ready" },
  { id: "rep006", name: "Mar 2024 District Report", generated: "2024-04-01", by: "Admin Suresh", size: "2.1 MB", status: "Ready" },
]

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-gray-900 flex items-center gap-2">
          <FileBarChart className="h-5 w-5 text-blue-600" />
          Reports & Analytics
        </h2>
        <p className="text-gray-500 text-sm">Generate, download, and share program reports</p>
      </div>

      {/* Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {reportCards.map((report) => (
          <Card key={report.title} className="hover:shadow-md transition-shadow">
            <CardHeader className="pb-2">
              <div className="flex items-start justify-between">
                <CardTitle className="text-sm font-semibold text-gray-900">{report.title}</CardTitle>
                <Badge variant="secondary" className="text-xs ml-2 shrink-0">{report.type}</Badge>
              </div>
              <CardDescription className="text-xs mt-1">{report.desc}</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between text-xs text-gray-500 mb-4">
                <span>Period: {report.period}</span>
                <span>~{report.size}</span>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" className="flex-1 gap-1.5 text-xs">
                  <RefreshCw className="h-3 w-3" />Generate
                </Button>
                <Button size="sm" className="flex-1 gap-1.5 text-xs">
                  <Download className="h-3 w-3" />Download
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Recent Reports Table */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Recently Generated Reports</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Report Name</TableHead>
                <TableHead>Generated Date</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Size</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentReports.map((report) => (
                <TableRow key={report.id}>
                  <TableCell className="font-medium text-sm text-gray-900">{report.name}</TableCell>
                  <TableCell className="text-sm text-gray-600">
                    {new Date(report.generated).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}
                  </TableCell>
                  <TableCell className="text-sm text-gray-700">{report.by}</TableCell>
                  <TableCell className="text-sm text-gray-600">{report.size}</TableCell>
                  <TableCell><Badge variant="success">{report.status}</Badge></TableCell>
                  <TableCell>
                    <Button variant="ghost" size="sm" className="gap-1.5 text-xs text-blue-600">
                      <Download className="h-3.5 w-3.5" />Download
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
